### ISSUE TITLE
Text cursor keeps blinking, even though window is not focussed

### ISSUE THREAD

**Issue by DarkTrick** [wereturtle/ghostwriter#482] opened 2019-12-05 02:55 UTC
**Platform (please complete the following information):**
- Linux XUbuntu 19.10 
- Desktop environment: xfce 4.14

**ghostwriter installation (please complete the following information):**
 - ghostwriter version: 1.7.4
 - installation type: deb file from official repos

**Describe the bug**
Text cursor keeps blinking, even though the window is not focussed.

**To Reproduce**
1. Open ghostwriter.
2. write a little.
3. Switch to a different window. (Mouseclick or Alt+Tab, both is ok)

**Actual behavior**
4. The text cursor keeps blinking.

**Expected behavior**
4. The text cursor inside of ghostwriter should become invisible.

**Comment by abenson** [comment] 2019-12-05 03:02
Duplicate of #447 <https://github.com/wereturtle/ghostwriter/issues/447>,
closed via 9a4ce5e
<https://github.com/wereturtle/ghostwriter/commit/9a4ce5ef393c9a06ba33c12ef4c18399bc8d1345>
.


Should be fixed in the next release.

**Comment by DarkTrick** [comment] 2019-12-05 06:02
Odd, that the search did not show any results...
I would close the issue then?

**Closed** 2020-01-26 17:02 UTC
