### ISSUE TITLE
Cannot export with Pandoc 2.0 

### ISSUE THREAD

**Issue by Spacetchi** [wereturtle/ghostwriter#304] opened 2018-02-25 07:00 UTC
Attempting to use Pandoc versions greater than 2.0 to view an HTML preview or export with smart typography yields this error with no way to proceed: 

> Export failed: --smart/-S has been removed. Use +smart or -smart extension instead. For example: pandoc -f markdown+smart -t markdown-smart. Try pandoc --help for more information.

(on Arch Linux with Pandoc 2.1.1)

**Comment by wereturtle** [comment] 2018-02-25 20:50
This is a duplicate of #260.  Don't worry.  The fix is already on the master branch and will be released soon (TM).

**Closed by wereturtle** 2018-02-25 20:50 UTC
Labels: bug, duplicate
