### ISSUE TITLE
Pandoc 2.1.1 for preview or export not working

### ISSUE THREAD

**Issue by andi-blafasl** [wereturtle/ghostwriter#303] opened 2018-02-15 10:39 UTC
Using pandoc 2.1.1 for export or preview does not work in gostwriter 

The following error message is show:

```
Export failed: --smart/-S has been removed. Use +smart or -smart extension instead. For example: pandoc -f markdown+smart -t markdown-smart. Try pandoc --help for more information.
```

For export you can disable the option "Smart Typography" and make the export work.

Is it possible to configure the parameters used for the export, or are they hardcoded in the app?

Best regards,
Andreas

**Comment by abenson** [comment] 2018-02-15 23:14
Duplicate of #260. I believe this will be fixed in the next release, which it sounds like will be soonish!

**Closed** 2018-02-21 07:24 UTC
Labels: bug, duplicate
