### ISSUE TITLE
Copy and paste thrown weirds chars in Ghostwriter.

### ISSUE THREAD

**Issue by felipehw** [wereturtle/ghostwriter#509] opened 2020-05-08 13:27 UTC
I'm a Brazilian Portuguese native speaker.
When I copy and paste texts with "Portuguese special chars", Ghostwriter puts strange symbols instead.
This doesn't happen with Apostrophe.

An example: I copy the initial paragraphs of [this text](https://www.terra.com.br/noticias/coronavirus/lockdown-por-coronavirus-ja-atinge-68-milhoes-no-brasil,8fcfce37fc98561ee35b66f72b16ee68ntjeb1d1.html) at both editors (Ghostwriter and Apostrophe) and we can see the problem:

![apostrophe - ghostwriter](https://user-images.githubusercontent.com/4523897/81409847-3c961c00-9116-11ea-8b83-025fb9589274.png)

- Ghostwriter 1.8.0 (Flatpak version)
- Fedora 32 + Wayland + Gnome 3.36.2

**Comment by tonghuix** [comment] 2020-05-08 15:58
Same version at Ubuntu 20.04, can not reproduce this bug. Does other Qt apps have the same problem?

![Screenshot from 2020-05-08 11-57-00](https://user-images.githubusercontent.com/423703/81423995-39555d00-9123-11ea-9cf6-f502003dc668.png)

**Comment by felipehw** [comment] 2020-05-08 20:27
@tonghuix Do you know other software using qt at Flathub?
I'm using Silverblue and I can't restart the machine.

**Comment by felipehw** [comment] 2020-05-08 20:32
I don't have many Qt apps.
But I tested with Kate (KDE editor) and ... no problem.
Just with Ghostwriter.

![Untitled](https://user-images.githubusercontent.com/4523897/81446836-ee067300-9151-11ea-8317-e43ee01cf354.png)

**Comment by wereturtle** [comment] 2020-05-31 23:36
I'm afraid I can't replicate this issue.  When I copy/paste that exact text you linked into ghostwriter, all characters are preserved.  I wonder if Wayland is the issue?  Not all Qt functionality is perfectly ported to Wayland just yet.

**Comment by wereturtle** [comment] 2020-05-31 23:42
I just switched to a Gnome Wayland session on my own Fedora 32 install.  I still can't replicate the error.  I am likewise running on Fedora 32, but with the KDE spin.  (Oddly, I also get Gnome desktop for free.)  Is there any other difference in platform configuration that anyone can think of that would cause this issue?

**Comment by wereturtle** [comment] 2020-05-31 23:46
I also just tried out the Flathub version.  I can't replicate the bug there, either.

**Comment by felipehw** [comment] 2020-06-01 14:49
I installed a Fedora 32 in Gnome Boxes and tried with Ghostwriter from RPM Fedora Official Repo and Flathub.

I replicated the problem without hiccups.

The problem only exists in the Flatpak build.

Look at the screenshot. The left window, perfect, is the RPM version. The right window is Flatpak and the problem shows its ugly face :)

![Screenshot from 2020-06-01 11-42-57](https://user-images.githubusercontent.com/4523897/83420945-bbbcfe00-a3fd-11ea-9f6f-2b4e058e6cf7.png)

**Comment by felipehw** [comment] 2020-09-18 18:47
After some months, today I tested with Flatpak in Xorg. There is no problem.
I only have this problem with Wayland ...

**Comment by wereturtle** [comment] 2020-10-18 01:57
Since this appears to be a Flatpak/Flathub issue that is entirely out of my hands, I am closing this issue.  Please report the issue instead to the Flatpak/Flathub developers, as I am sure this issue would affect multiple Qt applications.

**Closed by wereturtle** 2020-10-18 01:57 UTC
Labels: flatpak, troubleshoot
