### ISSUE TITLE
Ghostwriter/pandoc interaction broken again

### ISSUE THREAD

**Issue by Duoxilian** [wereturtle/ghostwriter#488] opened 2020-01-13 19:46 UTC
**Platform (please complete the following information):**
 - Ubuntu 18.04, Gnome 

**ghostwriter installation (please complete the following information):**
 - ghostwriter version [see Help->About in menu bar]: 1.8.0
 - If Linux, installation type [e.g., Flatpak, PPA, private build]: PPA

**Describe the bug**
The issue described in #260 seems to have resurfaced with pandoc 2.9.1.1.

Preview again reports `Export failed: --smart/-S has been removed. Use +smart or -smart extension instead. For example: pandoc -f markdown+smart -t markdown-smart. Try pandoc --help for more information.`. Using export can be made to work by turning smart features off.

**To Reproduce**
1. Use ghostwriter 1.8.0 and pandoc 2.9.1.1
2. Open a document and attempt to preview

**Comment by wereturtle** [comment] 2020-01-26 16:55
I'm not getting this error with pandoc 2.9.  Would you please provide the output of the following command?  I want to see if maybe the version printout is different on your system than mine:
```
$ pandoc --version
```

**Comment by happycoder97** [comment] 2020-02-22 10:22
pandoc 2.9.2

**Comment by lastweakness** [comment] 2020-03-31 17:48
Same issue with 2.9.2.1

**Comment by wereturtle** [comment] 2020-04-05 20:26
I left instructions above for checking the command line, to help me see what the output text is from pandoc.  Would either of you please post your results here?  Thanks!

**Comment by lastweakness** [comment] 2020-04-08 16:57
> I left instructions above for checking the command line, to help me see what the output text is from pandoc. Would either of you please post your results here? Thanks!

```bash
~ ❯ pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.4
Default user data directory: /home/fushinari/.local/share/pandoc or /home/fushinari/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by happycoder97** [comment] 2020-04-11 17:42
My version:
```bash
$ pandoc --version
pandoc 2.9.2.1
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.4
Default user data directory: /home/farzeen/.local/share/pandoc or /home/farzeen/.pandoc
Copyright (C) 2006-2020 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by happycoder97** [comment] 2020-04-26 06:00
I removed the pandoc from pacman, and installed pandoc-bin from AUR.
Now it works as expected.
```
$ pandoc --version
pandoc 2.9.2
Compiled with pandoc-types 1.20, texmath 0.12.0.1, skylighting 0.8.3.2
Default user data directory: /home/farzeen/.local/share/pandoc or /home/farzeen/.pandoc
Copyright (C) 2006-2019 John MacFarlane
Web:  https://pandoc.org
This is free software; see the source for copying conditions.
There is no warranty, not even for merchantability or fitness
for a particular purpose.
```

**Comment by lastweakness** [comment] 2020-04-26 07:04
> I removed the pandoc from pacman, and installed pandoc-bin from AUR.
> Now it works as expected.

I removed the version check from the code instead.

**Comment by happycoder97** [comment] 2020-04-30 07:01
@lastweakness Which version check? 
Both the pacman version and AUR version are 2.9.2 right?

**Comment by happycoder97** [comment] 2020-04-30 07:03
Also, I found out that the AUR version works by accident. 
The pacman version was slow because it used dynamic linking and haskell binaries' rpath is very huge, leading to unacceptably slow launch times. The AUR version is statically linked.
I'm surprised that it works, the older error message said `--smart/-S` option is removed.

**Comment by lastweakness** [comment] 2020-04-30 09:24
> @lastweakness Which version check?
> Both the pacman version and AUR version are 2.9.2 right?

I recompiled ghostwriter by removing the checks in ghostwriter's source and it works for now. But yeah, it's slow, so I'm also about to try the AUR version instead.

**Comment by richo67** [comment] 2020-05-12 11:49
> > @lastweakness Which version check?
> > Both the pacman version and AUR version are 2.9.2 right?
> 
> I recompiled ghostwriter by removing the checks in ghostwriter's source and it works for now. But yeah, it's slow, so I'm also about to try the AUR version instead.

Would it be possible to merge the change and make the release?

**Comment by lastweakness** [comment] 2020-05-12 12:37
> > > @lastweakness Which version check?
> > > Both the pacman version and AUR version are 2.9.2 right?
> > 
> > 
> > I recompiled ghostwriter by removing the checks in ghostwriter's source and it works for now. But yeah, it's slow, so I'm also about to try the AUR version instead.
> 
> Would it be possible to merge the change and make the release?

No, i don't think so. It will break previewing and exporting for users with older versions of pandoc. I think this is one of those cases were using the flatpak is clearly more stable. I switched to Apostrophe for the most part but Ghostwriter is still amazing.

**Comment by richo67** [comment] 2020-05-13 16:08
Is the problem identify? What is the issue? is it that pandoc has changed interface/command line is that an issue? If yes wouldn't it be best to have the command line in config file easily to be adjusted?

**Comment by JohnBlood** [comment] 2020-05-17 12:28
I have the same problem when I try to export a markdown file to epub. I'm going this on a clean install of Fedora 32. I installed ghostwriter through the Software Center. Pandoc is verion 2.7.3. 

If I turn of Smart Typography the error does not occur.

**Comment by lastweakness** [comment] 2020-05-17 15:18
> I have the same problem when I try to export a markdown file to epub. I'm going this on a clean install of Fedora 32. I installed ghostwriter through the Software Center. Pandoc is verion 2.7.3.
> 
> If I turn of Smart Typography the error does not occur.

So, you're on the flatpak version and this happens??

**Comment by JohnBlood** [comment] 2020-05-17 16:21
> So, you're on the flatpak version and this happens??

Sorry, I misspoke I installed ghostwriter from the terminal and it grabbed ghosterwriter from the Fedora repos. Sorry for the confusion.

**Comment by lastweakness** [comment] 2020-05-19 16:27
To anyone else facing this issue, @happycoder97 has said the right solution above. Use `pandoc-bin` from the AUR instead of `pandoc` from the community repo. If you're on some other distro, do whatever has the same effect, i.e. to use a binary-only version of `pandoc`.

**Comment by richo67** [comment] 2020-05-20 07:07
I am sorry but I still do not understand what is the cause of the problem, would somebody please explain to me? Thanks you.

**Comment by lastweakness** [comment] 2020-05-20 14:40
> I am sorry but I still do not understand what is the cause of the problem, would somebody please explain to me? Thanks you.

What distribution are you on?

On Arch, the issue is that the official pandoc package for Arch is packaged in a way that it depends on every single haskell library that's used to compile pandoc through dynamic linking instead of simply giving pandoc in a bnary format. This makes it slow and introduces weird bugs for programs depending on pandoc, as seen in this case. The easy fix is to remove `pandoc` and install `pandoc-bin` from the AUR. That puts an end to all such weird issues.

**Comment by richo67** [comment] 2020-05-21 07:20
Thanks understood. I did install pandoc-bin I am on Manjaro also using AUR.

**Comment by happycoder97** [comment] 2020-05-26 08:39
I have been facing this issue again randomly. I have no idea why this happens. At this moment it works, but sometimes it does show the --smart related error

**Comment by fushinari** [comment] 2020-05-26 17:15
> I have been facing this issue again randomly. I have no idea why this happens. At this moment it works, but sometimes it does show the --smart related error

It's the opposite for me. It works fine and fast even with `pandoc` (instead of `pandoc-bin`) on one of my Arch installations.

**Comment by happycoder97** [comment] 2020-05-27 06:31
@fushinari do you have an SSD? The issue with haskell binaries in pacman is related to something caled rpath variable inside the ELF file. I don't know the exact problem, but I read that list of folders in rpath is too long when you link haskell apps dynamically, causing the elf loader to take a lot of time finding the libraries it need. So if you have an SSD this overhead will be negligible.

**Comment by fushinari** [comment] 2020-05-27 06:37
> @fushinari do you have an SSD? The issue with haskell binaries in pacman is related to something caled rpath variable inside the ELF file. I don't know the exact problem, but I read that list of folders in rpath is too long when you link haskell apps dynamically, causing the elf loader to take a lot of time finding the libraries it need. So if you have an SSD this overhead will be negligible.

I have an HDD. I have two installations of Arch for KDE and GNOME separately that share a lot of things like package cache through symlinks and config files. On the GNOME installation, `pandoc` works fine and fast, but on the KDE installation, only `pandoc-bin` works well.

**Comment by fushinari** [comment] 2020-05-27 06:38
> @fushinari do you have an SSD? The issue with haskell binaries in pacman is related to something caled rpath variable inside the ELF file. I don't know the exact problem, but I read that list of folders in rpath is too long when you link haskell apps dynamically, causing the elf loader to take a lot of time finding the libraries it need. So if you have an SSD this overhead will be negligible.

I have an HDD. I have two installations of Arch for KDE and GNOME separately that share a lot of things like package cache through symlinks and config files. On the GNOME installation, `pandoc` works fine and fast, but on the KDE installation, only `pandoc-bin` works well.

**Comment by wereturtle** [comment] 2020-06-01 00:11
> > @lastweakness Which version check?
> > Both the pacman version and AUR version are 2.9.2 right?
> 
> I recompiled ghostwriter by removing the checks in ghostwriter's source and it works for now. But yeah, it's slow, so I'm also about to try the AUR version instead.

@fushinari  Would you mind please putting in some debug printing to see what version ghostwriter thinks it's reading from the pandoc output?  I'm curious to see what version it thinks it is.  I'm on Fedora and cannot reproduce this.  Even though it looks like an Arch issue, I'd like ghostwriter to be a little more robust than that.

**Comment by fushinari** [comment] 2020-06-01 03:32
> > I recompiled ghostwriter by removing the checks in ghostwriter's source and it works for now. But yeah, it's slow, so I'm also about to try the AUR version instead.
> 
> @fushinari Would you mind please putting in some debug printing to see what version ghostwriter thinks it's reading from the pandoc output? I'm curious to see what version it thinks it is. I'm on Fedora and cannot reproduce this. Even though it looks like an Arch issue, I'd like ghostwriter to be a little more robust than that.

It's not entirely an Arch issue. And I can't figure out what exactly went wrong. Like I've mentioned, my GNOME Arch setup works just fine with `pandoc` (not `pandoc-bin`) and without removing the checks. But my KDE Arch setup gives the "+smart/-smart" error without removing the checks. If I remove the checks, it works unbearably slowly. If I just use `pandoc-bin` instead, everything works normally even without removing the checks. I'd like to debug this further, so I'll report back later.

**Comment by fushinari** [comment] 2020-06-01 10:18
@wereturtle So.... after confirming that it didn't work with `pandoc` at first, I tried adding the debug statement. I recompiled and re-installed and imagine my surprise when it works perfectly this time. Major version is correctly 2 and minor version is also 9. Now, I removed the print statement and recompiled... `pandoc` works excellently with ghostwriter now and I have no idea how. It's fast too, just like pandoc-bin. Basically, I can't reproduce the issue anymore...

**Comment by fushinari** [comment] 2020-06-08 05:09
@wereturtle I have logs:
```
QtWebEngine::initialize() called with QCoreApplication object already created and should be call before. This is depreciated and may fail in the future.
QProcess: Destroyed while process ("pandoc") is still running.
QProcess: Destroyed while process ("pandoc") is still running.
js: Uncaught SyntaxError: Unexpected token ']'
DictionaryVoikko(): No valid dictionaries were found
Major version: 0
Minor version: 0
```
Major version is 0 and minor version is 0. The QProcess for pandoc is getting destroyed for some reason.

**Comment by wereturtle** [comment] 2020-10-18 02:03
Well, I'm flabbergasted.  No idea why it's doing that.  Fun with Arch?  Since I'm stumped, I'm going to close this issue for now.  Let me know if you find anything else out that might help.  Thanks!

**Closed by wereturtle** 2020-10-18 02:03 UTC
Labels: more information needed

**Comment by fushinari** [comment] 2020-10-18 03:41
Actually, it's not just Arch, it breaks wherever pandoc uses dynamic linking or shared libraries. The fix is as simple as building pandoc as a single binary and using it with pandoc or in the case of Arch, you can just use the `pandoc-bin` Arch package.

**Comment by wereturtle** [comment] 2020-10-18 08:19
Good to know!  Thanks!
