### ISSUE TITLE
Word suggestions appear in a wrong place when using Mozc Japanese IME

### ISSUE THREAD

**Issue by Igetin** [wereturtle/ghostwriter#423] opened 2019-03-10 21:13 UTC
When writing text using [Mozc Japanese IME](https://github.com/google/mozc) in ghostwriter’s main view, the word suggestion box always appears in the top left corner of the screen:

![mozc_ghostwriter](https://user-images.githubusercontent.com/14016863/54091188-b5b8a880-4385-11e9-8bb0-8135b085d91b.png)

The box displays in the correct position in all of my other software. It is supposed to appear right below the position of the text cursor. For example, in FocusWriter — which uses the same QT version as ghostwriter (5.9.5) — the box appears where it should:

![mozc_focuswriter ](https://user-images.githubusercontent.com/14016863/54091212-09c38d00-4386-11e9-97bd-97ae99a4d0f9.png)

I have no developing experience in QT, but I’m guessing ghostwriter does something funky in the main edit view, which causes Mozc to not find the actual position of the cursor. The suggestion box appears correctly in other parts of ghostwriter (like in the find and replace dialogs).

The problem is rather annoying because Mozc is my preferred method of writing Japanese. Just to clarify: the suggestion box always appears in the top left corner of the primary monitor, regardless of the dimensions and location of the ghostwriter window.

Additional information:
* ghostwriter version: 1.7.4 (from the [PPA](https://launchpad.net/~wereturtle/+archive/ubuntu/ppa))
* Mozc version: 2.20.2673.102
* Operating system: Xubuntu 18.04
* Input method: fcitx 4.2.9.6

**Comment by wereturtle** [comment] 2019-03-16 18:19
Duplicate of #382

**Closed by wereturtle** 2019-03-16 18:19 UTC
Labels: bug, duplicate

**Comment by Igetin** [comment] 2019-03-16 18:22
Oh, sorry about the duplicate. I only searched for “mozc” in the issues but not for “ime”.
