### ISSUE TITLE
And again... problems with math inserts

### ISSUE THREAD

**Issue by maxborowsky** [wereturtle/ghostwriter#462] opened 2019-09-08 06:08 UTC
Ghostwriter 1.8.0
Pandoc 2.2.1
Fedora 30
![Screenshot from 2019-09-08 09-01-06](https://user-images.githubusercontent.com/20723033/64484187-49750f80-d217-11e9-81b3-5e09d1519d0a.png)
At the same time, **pandoc** utility correctly converts this md file to html both with the **--mathjax** option and the **--mathml** option.

**Comment by wereturtle** [comment] 2019-09-23 17:24
Duplicate of #443

**Closed by wereturtle** 2019-09-23 17:24 UTC
Labels: bug, duplicate
