### ISSUE TITLE
Highlighting Support for Pandoc YAML Metadata?

### ISSUE THREAD

**Issue by interstellarshadow** [wereturtle/ghostwriter#192] opened 2017-03-13 20:55 UTC
So when writing metadata for a markdown file, I like to use Pandoc's YAML metadata, because it delimits it from the rest of the text well, and allows for custom fields. However, ghostwriter renders the metadata like a header rather than somehow indicating that it's metadata.

```
---
author: interstellarshadow
title: This is a Metadata Block
---
```

This will render as

```
--------------------------------------------------------------
author: interstellarshadow 
## title: This is a Metadata Block
```

in the editor

**Comment by jmhibben** [comment] 2017-03-13 21:56
This is how I use YAML to avoid that particular rendering issue:

```
---
author: interstellarshadow
title: This is a Metadata Block
...
```

I agree, though- highlighting YAML as intended would be nice, and help to further distinguish the metadata block from the rest of the document.

**Comment by wereturtle** [comment] 2017-04-09 18:42
Since there is a workaround, I am going to close this issue.  *ghostwriter* strives to have wide arms, meaning that the widest accepted syntax for Markdown is favored in syntax highlighting.  Unfortunately, most Markdown flavors do not recognize Pandoc's YAML, and will render the last `---` separator as a heading--which is precisely what *ghostwriter* does.  Come to think of it, this is probably why Pandoc allows for YAML blocks to end with a `...` separator.

**Closed by wereturtle** 2017-04-09 18:42 UTC
Labels: enhancement, wontfix
