### ISSUE TITLE
Create new file if file parameter file does not exist.

### ISSUE THREAD

**Issue by hirschenberger** [wereturtle/ghostwriter#173] opened 2017-01-09 15:02 UTC
If executed ghostwriter from the commandline with a file parameter that does not exist, ghostwriter says it can't find the file and quits.
As most editors do, ghostwriter should create a new empty file and open it.

I can create a PR if you like the feature.

**Comment by wereturtle** [comment] 2017-01-22 00:53
Duplicate of #165.  I've reopened that issue.

**Closed by wereturtle** 2017-01-22 00:53 UTC
Labels: duplicate, enhancement
