### ISSUE TITLE
Typing with text selected breaks preview

### ISSUE THREAD

**Issue by Luke-Nukem** [wereturtle/ghostwriter#119] opened 2016-08-13 09:34 UTC
As per title.

Steps to reproduce:

1. Open a document, have a preview open next to it.
2. Select some text, something short (a word or two) will do.
3. Start typing.
4. Preview now ends where the typing was started / text selected.

OS: openSUSE Linux Tumbleweed
Version: Release 1.4

**Comment by wereturtle** [comment] 2016-08-14 20:10
Hi Luke,

Are you saying that the text after the typing started disappeared from the preview window?  Or that the preview scrolled to that point?  (The latter is expected behavior, as it is supposed to compare line by line the new preview output with the old, and then scroll to the first difference it finds in the preview window.)

Also, what exporter are you using?  Pandoc?  MultiMarkdown?  The built-in Sundown?

Finally, is there some sample text you can engineer to help me replicate this?  I could use a more concrete example.

Thanks!

**Comment by Luke-Nukem** [comment] 2016-08-14 21:18
@wereturtle Strange, it is not doing it now. Previously, if I had text selected and then started typing, the *selected text* would remain in place, still highlighted, and then the preview would break in that place (i.e, nothing rendered after that spot).

I've tried a few steps to replicate it, and it just doesn't seem to happen now.

* Select text and type.
* Copy/paste a doc in, repeat first step.
* Remove all configs (Ithought perhaps it was to do with first use), then repeat first step.
* Type a lengthy md after removing configs, repeat first step.

So I'm drawing a blank now, the steps above are all i can think of that lead up to what I experienced. Close the issue?

**Comment by wereturtle** [comment] 2016-08-14 21:38
OK, I'll close it.  Feel free to open a new issue if you are able to replicate the problem again.  Thanks!

**Comment by wereturtle** [comment] 2016-08-19 07:14
I have now observed the behavior.  It seems to happen when there is a null character in the middle of the text.  This causes the Markdown processor to stop processing past that point.  How the null character got there is beyond me.  This may be related to #115, and it may be the case that a residual junk null character made it into the text due to this bug.  However, I could swear this happened during one session with a chunk of text I had freshly edited with the fix to #115 in the build already.  I'm reopening this issue to keep an eye on it, and to see if anybody else can notice a pattern with a null character slipping into the text.

The workaround in the meantime is to backspace on the spot where the preview chops off, and get rid of the null character.

**Closed** 2016-08-24 06:45 UTC
Labels: bug, hotfix, ready
