### ISSUE TITLE
Error when building using make - Update

### ISSUE THREAD

**Issue by Pieber** [wereturtle/ghostwriter#415] opened 2019-02-04 20:08 UTC
Hi!

I am currently using Debian 9.6.

I encountered the following error after taping `make`:

`make: /usr/lib/x86_64-linux-gnu/qt5/bin/lrelease: Command not foundMakefile:623: recipe for target 'build/release/translations/ghostwriter_cs.qm' failedmake: *** [build/release/translations/ghostwriter_cs.qm] Error 127`

To fix my problem:
```
sudo apt-get install qttools5-dev-tools
sudo apt-get install libminiupnpc-dev
```
[](https://stackoverflow.com/questions/20450893/usr-lib-i386-linux-gnu-qt5-bin-lrelease-not-found-warning-target-is-empty)

Can you update the current documentation concerning the build step on Linux?

Regards,
Pieber

**Comment by wereturtle** [comment] 2019-02-12 06:59
Duplicate of #410

**Closed by wereturtle** 2019-02-12 06:59 UTC
Labels: documentation, duplicate
