### ISSUE TITLE
menu font size too small

### ISSUE THREAD

**Issue by ggrrll** [wereturtle/ghostwriter#612] opened 2021-05-21 08:16 UTC
**Platform**
 -  Linux, mint 20.1 
 -   Cinnamon 4.8.6

**ghostwriter**
 - ghostwriter 2.0.0-rc5

**Describe the bug**
application (menus, etc...) font is too small

**Expected behavior**
bigger font size

**Comment by wereturtle** [comment] 2021-05-27 07:13
Please try launching ghostwriter from a terminal window with the QT_DEVICE_PIXEL_RATIO environment variable set:

    $ QT_DEVICE_PIXEL_RATIO=2 ghostwriter

You will want to set it to the DPI ratio of your monitor.  Note that I've had issues in the past with fractional values (a la "1.5"), so stick to integral values, like 2 or 4, for now.

If this resolves the issue, then the problem is with Cinnamon.  Which wouldn't surprise me because GTK-based distro flavors tend to forget the DPI settings for Qt apps.  :(

For more information on the Cinnamon DPI scaling factor issue, see [this bug report here](https://github.com/linuxmint/cinnamon-settings-daemon/issues/135)

**Comment by wereturtle** [comment] 2021-05-27 07:21
Duplicate of #610.  Will continue discussions there.

**Closed by wereturtle** 2021-05-27 07:21 UTC
Labels: bug, duplicate

**Comment by ggrrll** [comment] 2021-05-27 08:05
ok, thanks for the suggestion

I have actually uninstalled GW as in the last version it was crashing often
