### ISSUE TITLE
Non-ASCII characters not displayed in the outline

### ISSUE THREAD

**Issue by ASGusev** [wereturtle/ghostwriter#622] opened 2021-06-10 09:45 UTC
**Platform**: Ubuntu 20.04, Gnome
**ghostwriter version**: 2.0.1, installed from PPA

Outline fails to show non-ASCII characters.

**To Reproduce**
1. Create new file 
2. Create a header with non-latin characters
3. Question marks are displayed instead of these characters in the outline

**Expected behavior**
The header displayed correctly like latin headers.

**Screenshots**
![изображение](https://user-images.githubusercontent.com/5954975/121503046-6096f180-c9e9-11eb-9f0d-e5844b1826e2.png)

**Additional context**
Cyrillic characters were used in a UTF-8 file: [headers.md](https://github.com/wereturtle/ghostwriter/files/6630174/headers.md).

**Comment by wereturtle** [comment] 2021-06-17 18:40
Duplicate of #615.

**Closed by wereturtle** 2021-06-17 18:40 UTC
Labels: duplicate
