### ISSUE TITLE
Selected text fail to replace

### ISSUE THREAD

**Issue by alfsb** [wereturtle/ghostwriter#120] opened 2016-08-14 14:16 UTC
I only type 'd' on this example:
![ddd](https://cloud.githubusercontent.com/assets/10078152/17649636/62b71724-6210-11e6-91ba-20c3fffb0c4c.gif)

Possible related #119

**Comment by wereturtle** [comment] 2016-08-14 20:05
Hi @alfsb,

To confirm whether this issue is related to #115, can you try turning off the "Automatically match characters while typing" option under Settings?  Does the issue still occur?  (This is a workaround for #115.)

I discovered that the bug in #115 is due to a lack of boundary checking with this feature when hitting the backspace key.  I have the fix for #115, but I would like to confirm whether the issue you are describing here is caused by the same thing.  Perhaps some text buffer corruption occurred.

I only ask because I am having difficulty replicating what you are describing.  But again, perhaps it's related to #115, and I just haven't managed to corrupt the text buffer yet to trigger this issue.

Thanks!

**Comment by alfsb** [comment] 2016-08-14 23:11
Hi @wereturtle ,

With "Automatically match characters while typing" disabled the bug not occurs. As noted on #115, it's necessary first to trigger 115, so this occurs. So it's really related.

**Comment by wereturtle** [comment] 2016-08-15 15:57
OK then, I will close this issue.  Go ahead and download the new 1.4.1 version, which has the patch for #115, and should thus fix this issue as well.

Thanks!

**Closed by wereturtle** 2016-08-15 15:57 UTC
