### ISSUE TITLE
Math is not rendering on the preview window

### ISSUE THREAD

**Issue by funnisquares** [wereturtle/ghostwriter#764] opened 2022-05-02 03:25 UTC
**Platform (please complete the following information):**
 - OS and version:  Manjaro 21
 - If Linux, Desktop Environment: Plasma (With awesomewm)

**ghostwriter installation (please complete the following information):**
 - ghostwriter version: 2.1.1
 - If Linux, installation type: Manjaro's community repo 

**Describe the bug**
Math is not rendering on HTML preview with Pandoc selected as the markdown flavor (or any other markdown flavor).

**To Reproduce**
1. Write a math expression
2. See that the expression is not rendered on the preview window

**Expected behavior**
The math renders correctly

**Screenshots**
![image](https://user-images.githubusercontent.com/43013384/166180533-67df8483-efab-46fb-9c3b-f50a317f9d53.png)

**Comment by DamienC35** [comment] 2022-05-02 11:27
I had the same issue exactly (with Linux/Mint). I solved it by downloading the last *pandoc* releas (2.18).

**Comment by funnisquares** [comment] 2022-05-02 21:34
Did not work for me. Either _pandoc_ 2.17.1.1 or 2.18 does not work.

**Comment by wereturtle** [comment] 2022-05-28 20:47
I'm on Fedora/Plasma 5 with Pandoc 2.14 installed. I cannot reproduce this issue.  What version of Pandoc are you running?

**Comment by wereturtle** [comment] 2022-06-18 19:23
Closing this issue as there was no reply from the author after two weeks.

**Closed by wereturtle** 2022-06-18 19:23 UTC
Labels: bug, troubleshoot
